/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ivanovpv.timeseries.form;

import com.ivanovpv.timeseries.repository.InFluxRepository;
import com.ivanovpv.timeseries.tableModel.TestTableModel;
import com.ivanovpv.timeseries.tableModel.TrendTableModel;
import com.ivanovpv.timeseries.interfaces.TrendRepository;

import javax.swing.*;

/**
 *
 * @author Pavel
 */
public class MainApp extends javax.swing.JFrame {
    TrendRepository repository;
    public MainApp() {
        //repository = new MySQLRepository();
        repository = new InFluxRepository();
        initComponents();
        trendTable.setModel(new TrendTableModel(repository));
        testTable.setModel(new TestTableModel(repository));

        trendTable.setDefaultEditor(Object.class, null);
        testTable.setDefaultEditor(Object.class, null);

        testTable.getSelectionModel().addListSelectionListener((event) -> {
            int idTest = -1;
            try {
                idTest = Integer.parseInt(testTable.getValueAt(testTable.getSelectedRow(), 0).toString());
            } finally {
                long ms = System.nanoTime();
                repository.setCurTest(idTest);
                ((TrendTableModel) trendTable.getModel()).updateData();
                ms = System.nanoTime() - ms;
                timeOfLoadingLbl.setText("Time of Loading: " + ms / 1_000_000 + " ms");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePicker = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        trendTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        importBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        timeOfValueAccessLbl = new javax.swing.JLabel();
        timeOfLoadingLbl = new javax.swing.JLabel();
        getStringBtn = new javax.swing.JButton();
        getLineSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        trendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        trendTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(trendTable);

        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(testTable);

        importBtn.setText("Import To DB");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        timeOfValueAccessLbl.setText("Time of Values access:");

        timeOfLoadingLbl.setText("Time of Loading:");

        getStringBtn.setText("Get Line");
        getStringBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStringBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(importBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getStringBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getLineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeOfLoadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(timeOfValueAccessLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importBtn)
                    .addComponent(deleteBtn)
                    .addComponent(timeOfValueAccessLbl)
                    .addComponent(timeOfLoadingLbl)
                    .addComponent(getStringBtn)
                    .addComponent(getLineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        repository.deleteCurTest();
        ((TrendTableModel) trendTable.getModel()).updateData();
        ((TestTableModel) testTable.getModel()).updateData();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        if(filePicker.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            repository.importToDB(filePicker.getSelectedFile().getAbsolutePath());
        }
        ((TrendTableModel) trendTable.getModel()).updateData();
        ((TestTableModel) testTable.getModel()).updateData();
    }//GEN-LAST:event_importBtnActionPerformed

    private void getStringBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStringBtnActionPerformed
        long ms = System.currentTimeMillis();
        trendTable.changeSelection((Integer) getLineSpinner.getValue(), 0, true, false);
        ms = System.currentTimeMillis() - ms;
        timeOfValueAccessLbl.setText("Time of Value access: " + ms + " ms");
    }//GEN-LAST:event_getStringBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JFileChooser filePicker;
    private javax.swing.JSpinner getLineSpinner;
    private javax.swing.JButton getStringBtn;
    private javax.swing.JButton importBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable testTable;
    private javax.swing.JLabel timeOfLoadingLbl;
    private javax.swing.JLabel timeOfValueAccessLbl;
    private javax.swing.JTable trendTable;
    // End of variables declaration//GEN-END:variables
}
